# Generated by Django 3.1.3 on 2020-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=120)),
                ('accno', models.CharField(max_length=120, unique=True)),
                ('acctype', models.CharField(max_length=120)),
                ('balance', models.IntegerField(default=3000)),
                ('phonenumber', models.CharField(max_length=12)),
                ('mpin', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
