# Generated by Django 3.1.3 on 2020-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpin', models.CharField(max_length=6)),
                ('accno', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='accno',
            field=models.CharField(max_length=15),
        ),
    ]
