# Generated by Django 3.1.3 on 2020-12-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=120)),
                ('recipe_img', models.ImageField(upload_to='images')),
                ('created_by', models.CharField(max_length=120)),
            ],
        ),
    ]
